### ISSUE TITLE
Salinity budget terms

### ISSUE THREAD

**Issue by adele157** [adele157/easterlies-collaborative-project#60]
Is the longer-term salinity change in the WIND+_meridional case driven by a) changes in brine rejection, or b) feedback from the overturning increase bringing more salty CDW onto the shelf? We know that the initial change is driven by brine rejection, but how much of a role does the advective feedback have in the longer term salinity increase?

<img width="400" alt="fig1_experimentalsetup" src="https://user-images.githubusercontent.com/8506963/152258584-d2d7b05f-c93c-4706-bbe7-3e62ad888071.jpg">

Ideas to investigate this:
- Plot spatial maps of the salinity and temperature in the WIND+_meridional case to see if they are aligned. If so, then likely the salinity is controlled by the same mechanism as the temperature (i.e. advective feedback).
- Do a rough budget estimate of the salinity change on the shelf from the overturning change using average CDW/DSW salinity values. Compare with change in surface FW fluxes.
- Rerun a year of WIND+_meridional and the CONTROL and output salinity advection terms to do the budget properly.

**Comment by wghuneke** [comment]
Plots of the bottom temperature and salinity fields (the temperature plot is Figure 10 from the paper).
![Figure10](https://user-images.githubusercontent.com/15355753/152291009-1ad67841-3021-4920-9c66-5a55c745944b.png)
![Figure10_salinity](https://user-images.githubusercontent.com/15355753/152291014-decf7fef-1dd5-4c99-a1ad-ffd3b7fcaebb.png)

**Comment by wghuneke** [comment]
Just looking at the WIND+merid case:
- the signs mostly align (warming=salinification and vice versa)
- exception: west of Prydz Bay
- amplitude between temperature and salinity varies though, example is Weddell Sea continental shelf

**Comment by AndyHoggANU** [comment]
Well, I’m reading this as the WIND+merid actually has quite a different temp/salinity anomaly signal in every location where DSW formation occurs — Weddell, Ross, Adelaide, Prydz and nearby. To me, this implies that the salt increase in those locations are not CDW-induced. 

But let’s cross-check with our back-of-the-envelope calculation.

**Comment by adele157** [comment]
There’s going to be a difference between the temp and salt anomalies in the DSW formation locations. Temperature has close to zero anomalies right at the formation sites, because there is still convection in all experiments and so the temperature is limited by and sits close to the freezing point in these connective regions.

**Comment by matthew-england-unsw** [comment]
Hi Adele & all - I agree that T will have close to zero anomalies at the surface where the convection is triggered, but the values at the bottom will include a mixture of waters deeper in the water column, so these bottom-most T anomalies will be influenced by subsurface onshore-offshore heat exchanges driven by the wind perturbations.  Can subsurface cross- or along-shelf heat exchange anomalies explain these patterns?

**Comment by AndyHoggANU** [comment]
OK, I think one of our tasks from the last meeting was to roughly calculate the magnitude of onshore salt transport due to CDW onshore flow. Let's make an upper bound of this calculation by assuming:

- The offshore flux of DSW (~9 Sv in control) is matched by the same onshore transport of CDW: Call this `Q`
- The difference between salinity of DSW and CDW is 0.2 g/kg (I think this is an upper bound): `dS`
- Shelf area is A = 3e12 m^3
- Reference density $\rho_0$ = 1000 kg/m^3
- Haline contraction coefficient $\beta$ = 8e-4 kg/g

Then, the effective buoyancy flux of CDW-DSW exchange, averaged over the whole shelf, is:

`\rho_0 Q dS \beta / A = 1000 * 9e6*0.2*8e-4/3e12 ~ 5 e-7 kg/s/m^2`

This is a small fraction of the peak buoyancy flux due to melt. But it happens all year, and the average melt buoyancy flux in the control is 1.1e-6 kg/s/m^2. So it is a similar order of magnitude. **Anyone want to check my maths??** 

The next step is to see if the change in Q with the perturbation produces a large change in onshore salt transport. This is simple -- the change in Q is ~1.5Sv, so 1/6th of the above: `8e-7 kg/s/m^2`. This is a similar size to the melt signal. But it is an upper bound (dS is likely smaller, and it's unlikely that all on-shelf flow is CDW, some is probably fresh AASW)

Conclusion: Likely, the effect of enhanced salt transport is a slightly smaller effect than the sea ice freshwater export upon the shelf salinity. But it's not negligible. This adds complexity to our story. Options for including this are either to suggest this is a possible mechanism or to calculate salt budgets exactly ....

**Comment by adele157** [comment]
I don't think this adds too much complexity. The initial change in DSW formation still has to be driven by sea ice changes, because the initial change in overturning is <<1.5Sv. So this overturning salt transport would only contribute as a feedback, not the initial driver. I think we could just leave it in the schematic and mention it in the discussion?

**Comment by AndyHoggANU** [comment]
Yeah, that works for me.

**Comment by adele157** [comment]
Summary from yesterday's discussion: 
We decided to remove the word 'salt' from panel b of the schematic, and then just discuss the possible overturning feedback in the discussion. The rough calculation is sufficient to know that the brine rejection forcing is a larger influence on the shelf salinity than the overturning feedback.
