### ISSUE TITLE
Velocity anomalies

### ISSUE THREAD

**Issue by wghuneke** [adele157/easterlies-collaborative-project#7]
- Maps of along-slope velocity (circumpolar)
- Along-slope velocity along 1000 m isobath

**Comment by wghuneke** [comment]
![Fig_ASC_map_easterlies_pert](https://user-images.githubusercontent.com/15355753/124868752-925ca180-e003-11eb-89a3-dc4a72420468.png)

**Comment by wghuneke** [comment]
Things to note:
- ASC is mostly negative, hence +ve anomalies indicate a slowdown of the ASC in the perturbation and -ve anomalies an acceleration
- Anomalies larger for easterly increase experiment -> not a linear response
- Easterly increase shows a slowdown - this is opposite to what I expected

**Comment by adele157** [comment]
Wilma is the top plot here the same as your Fig 2b in your paper? It's a little hard to tell due to the different projections, but they look quite different to me. This figure seems to show the coastal current as having much stronger velocities than the ASC, whereas your paper figure shows the opposite. Could it be the shorter averaging period here perhaps?

**Comment by wghuneke** [comment]
Interesting point. For the plot in the paper I used 10 years (2080-2089) whereas in the plot for this project I used 5 years (2160-2164). I plotted the difference on a circumpolar projection for comparison below. There are some differences in the Weddell Sea (weaker in the east, stronger in the west) and in the Amundsen Sea (weaker eastward current). But I'm not sure if the coastal current is stronger/weaker. The model does have a strong coastal current in East Antarctica.

![Screenshot_ASC_21602164_20802089](https://user-images.githubusercontent.com/15355753/125014208-9f839a00-e0b0-11eb-8216-b7c3324878a5.png)

**Comment by wghuneke** [comment]
I also plotted the along-slope velocity along the 1000m isobath so we can see the change in the depth structure. 
- You can nicely see that the bottom-intensified flows are stronger in the easterlies increase case which matches our results from the T/S plots [here](https://github.com/adele157/easterlies-collaborative-project/issues/4). And in the easterlies decrease the bottom flow decreases.
- You can also see the decrease (red) in the upper 500m velocity which we can see in the very first figure of this issue.

![Fig_ASC_1000m_contour_easterlies_pert](https://user-images.githubusercontent.com/15355753/125014485-2a649480-e0b1-11eb-8ccf-ee0ee1a28b55.png)

**Comment by adele157** [comment]
Great thanks for checking that - must have just been my eyes deceiving me thinking that the earlier 10 year period had a much stronger ASC.

In the 1000m isobath figure above, the increase/decrease perturbation anomalies look fairly symmetrical, is that right? But not in the map view at the top. Is that because the map view highlights the shelf changes (which are asymmetrical) more than the slope changes (which are symmetrical)?

I don't understand the sign of the changes here either. Even West Antarctica seems inconsistent with the wind changes - stronger easterlies which oppose the westward flowing current there result in a stronger westward flowing current. I guess there is a feedback which overwhelms the Ekman-driven heaving of the isopcynals against the coast ([as shown here](https://github.com/adele157/easterlies-collaborative-project/issues/10#issuecomment-875293942)) that we haven't identified yet.

Maybe one way to start trying to understand the dynamics here is to look at [cross-slope transects of velocities / isopycnals / temp / salt](https://github.com/adele157/easterlies-collaborative-project/issues/16).

**Comment by StephenGriffies** [comment]
How do you define along-slope velocity? Are you just projecting u into along and across the local direction of the topography slope?  I guess this definition becomes a bit noisy when there is only a weak slope, as on the shelf.  Is that correct?

**Comment by wghuneke** [comment]
Yes, I project onto the local topographic slope. I'm mostly interested in the ASC (which where the slope is large) and usually ignore the areas on the shelf / further offshore.

**Comment by wghuneke** [comment]
Vertical average of the upper 500 m (data along the 1000 m isobath), anomaly for each perturbation from the control run. Seems to be a symmetric response in most regions after all.
![Fig_ASC_1000m_contour_easterlies_pert_upper500m](https://user-images.githubusercontent.com/15355753/125711621-673d1226-9ca8-498b-b6de-840310b10a42.png)

**Comment by wghuneke** [comment]
Here are the plots for **year 1** (along 1000 m isobath) in comparison to the above plots which are an average over years 10-15.

- Overall similar response in year 1 compared to years 10-15 (that is same signs and spatial distribution)
- Pattern of change in the vertical is less pronounced -> fast barotropic response? It takes time for the dense shelf water to build up and show up as a signal near the continental slope...

![Fig_ASC_1000m_contour_easterlies_pert_year1](https://user-images.githubusercontent.com/15355753/125718464-4c3881eb-3e8e-44ac-a511-7150ceed258c.png)

![Fig_ASC_1000m_contour_easterlies_pert_upper500m_year1](https://user-images.githubusercontent.com/15355753/125718472-7f629dde-8c2e-46df-ae19-ac987c8660ee.png)
